steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 'deploy', 'api',
    '--allow-unauthenticated',
    '--trigger-http',
    '--runtime', 'nodejs8',
    '--region', '${_REGION}',
    '--memory', '128MB'
  ]
substitutions:
  _REGION: us-east1
